name: Sharepoint Upload
on:
  release:
    types: [edited, released]
  workflow_dispatch:
jobs:
  Date:
    runs-on: ubuntu-latest
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT
  Sharepoint:
    runs-on: ubuntu-latest
    needs: [Date]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Determine runner mounts
        run: |
          sudo echo -e "Disk freespace and mounts\n$(df -hT)\n\n$(mount)" | tee runner-disks.txt

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Validate Artifacts
        run: |
          echo -e "Artifacts Downloaded\n$(find . -type f -iname *sha -execdir sha256sum -c {} \;)"

      - name: Show Artifacts
        run: ls -1sh ${{ vars.COLLECTOR }}-*.*

      # Upload files to Sharepoint

      - name: Send Files to Sharepoint
        uses: amentumcms/sharepoint-file-upload-action@main
        with:
          file_path: "${{ vars.COLLECTOR }}-*.*"
          host_name: "${{ secrets.SHAREPOINT_HOST }}"
          site_name: "${{ secrets.SHAREPOINT_SITE }}"
          upload_path: "${{ secrets.SHAREPOINT_BASEPATH }}/${{ vars.COLLECTOR }}/${{ needs.Date.outputs.Date }}"
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_APP_ID }}
          client_secret: ${{ secrets.SHAREPOINT_APP_SECRET }}
          login_endpoint: "login.microsoftonline.us"
          graph_endpoint: "graph.microsoft.us"